spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: CHICKEN
    password: MUMANI
    driverClassName: oracle.jdbc.driver.OracleDriver

jwt:
  header: Gyemoim
  secret: GyemoimChickenMumani
  token-validity-in-seconds: 3600000


mybatis:
  mapper-locations: classpath:mapper/**.xml
#  type-aliases-package: com.team.gyemoim.mapper
