spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: CHICKEN
    password: MUMANI
    driverClassName: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath:mapper/**.xml