spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: CHICKEN
    password: MUMANI
    driverClassName: oracle.jdbc.driver.OracleDriver

jwt:
  header: Gyemoim
  secret: GyemoimChickenMumani
  token-validity-in-seconds: 1800000  # 30분


mybatis:
  mapper-locations: classpath:mapper/**.xml


upload:
    path: /path/to/upload/folder
